export interface Country {
  code: string;
  name: string;
  flag: string;
  phoneCode: string;
}

export interface City {
  name: string;
  country: string;
}

export const countries: Country[] = [
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', phoneCode: '+376' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', phoneCode: '+971' },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', phoneCode: '+93' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', phoneCode: '+1' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮', phoneCode: '+1' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', phoneCode: '+355' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', phoneCode: '+374' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', phoneCode: '+244' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', phoneCode: '+54' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸', phoneCode: '+1' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', phoneCode: '+43' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', phoneCode: '+61' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼', phoneCode: '+297' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', phoneCode: '+994' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', phoneCode: '+387' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', phoneCode: '+1' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', phoneCode: '+880' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', phoneCode: '+32' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', phoneCode: '+226' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', phoneCode: '+359' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', phoneCode: '+973' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', phoneCode: '+257' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', phoneCode: '+229' },
  { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱', phoneCode: '+590' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲', phoneCode: '+1' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', phoneCode: '+673' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', phoneCode: '+591' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', phoneCode: '+55' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', phoneCode: '+1' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', phoneCode: '+975' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', phoneCode: '+267' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', phoneCode: '+375' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', phoneCode: '+501' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', phoneCode: '+1' },
  { code: 'CD', name: 'Democratic Republic of the Congo', flag: '🇨🇩', phoneCode: '+243' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', phoneCode: '+236' },
  { code: 'CG', name: 'Republic of the Congo', flag: '🇨🇬', phoneCode: '+242' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', phoneCode: '+41' },
  { code: 'CI', name: 'Ivory Coast', flag: '🇨🇮', phoneCode: '+225' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', phoneCode: '+56' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', phoneCode: '+237' },
  { code: 'CN', name: 'China', flag: '🇨🇳', phoneCode: '+86' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', phoneCode: '+57' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', phoneCode: '+506' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', phoneCode: '+53' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻', phoneCode: '+238' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼', phoneCode: '+599' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', phoneCode: '+357' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', phoneCode: '+420' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', phoneCode: '+49' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', phoneCode: '+253' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', phoneCode: '+45' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', phoneCode: '+1' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', phoneCode: '+1' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', phoneCode: '+213' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', phoneCode: '+593' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', phoneCode: '+372' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', phoneCode: '+20' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', phoneCode: '+291' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', phoneCode: '+34' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', phoneCode: '+251' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', phoneCode: '+358' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', phoneCode: '+679' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰', phoneCode: '+500' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', phoneCode: '+691' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴', phoneCode: '+298' },
  { code: 'FR', name: 'France', flag: '🇫🇷', phoneCode: '+33' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', phoneCode: '+241' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', phoneCode: '+44' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', phoneCode: '+1' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', phoneCode: '+995' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫', phoneCode: '+594' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬', phoneCode: '+44' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', phoneCode: '+233' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮', phoneCode: '+350' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱', phoneCode: '+299' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', phoneCode: '+220' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', phoneCode: '+224' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵', phoneCode: '+590' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', phoneCode: '+240' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', phoneCode: '+30' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', phoneCode: '+502' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺', phoneCode: '+1' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', phoneCode: '+245' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', phoneCode: '+592' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', phoneCode: '+852' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', phoneCode: '+504' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', phoneCode: '+385' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', phoneCode: '+509' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', phoneCode: '+36' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', phoneCode: '+62' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', phoneCode: '+353' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', phoneCode: '+972' },
  { code: 'IM', name: 'Isle of Man', flag: '🇮🇲', phoneCode: '+44' },
  { code: 'IN', name: 'India', flag: '🇮🇳', phoneCode: '+91' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', phoneCode: '+964' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', phoneCode: '+98' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', phoneCode: '+354' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', phoneCode: '+39' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪', phoneCode: '+44' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', phoneCode: '+1' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', phoneCode: '+962' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', phoneCode: '+81' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', phoneCode: '+254' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', phoneCode: '+996' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', phoneCode: '+855' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', phoneCode: '+686' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', phoneCode: '+269' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', phoneCode: '+1' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', phoneCode: '+850' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', phoneCode: '+82' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', phoneCode: '+965' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾', phoneCode: '+1' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', phoneCode: '+7' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', phoneCode: '+856' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', phoneCode: '+961' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', phoneCode: '+1' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', phoneCode: '+423' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', phoneCode: '+94' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', phoneCode: '+231' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', phoneCode: '+266' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', phoneCode: '+370' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', phoneCode: '+352' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', phoneCode: '+371' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', phoneCode: '+218' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', phoneCode: '+212' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', phoneCode: '+377' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', phoneCode: '+373' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', phoneCode: '+382' },
  { code: 'MF', name: 'Saint Martin', flag: '🇲🇫', phoneCode: '+590' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', phoneCode: '+261' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', phoneCode: '+692' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', phoneCode: '+389' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', phoneCode: '+223' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', phoneCode: '+95' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', phoneCode: '+976' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴', phoneCode: '+853' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵', phoneCode: '+1' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶', phoneCode: '+596' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', phoneCode: '+222' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸', phoneCode: '+1' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', phoneCode: '+356' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', phoneCode: '+230' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', phoneCode: '+960' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', phoneCode: '+265' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', phoneCode: '+52' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', phoneCode: '+60' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', phoneCode: '+258' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', phoneCode: '+264' },
  { code: 'NC', name: 'New Caledonia', flag: '🇳🇨', phoneCode: '+687' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', phoneCode: '+227' },
  { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫', phoneCode: '+672' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', phoneCode: '+234' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', phoneCode: '+505' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', phoneCode: '+31' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', phoneCode: '+47' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', phoneCode: '+977' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', phoneCode: '+674' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺', phoneCode: '+683' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', phoneCode: '+64' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', phoneCode: '+968' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', phoneCode: '+507' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', phoneCode: '+51' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫', phoneCode: '+689' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', phoneCode: '+675' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', phoneCode: '+63' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', phoneCode: '+92' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', phoneCode: '+48' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲', phoneCode: '+508' },
  { code: 'PN', name: 'Pitcairn Islands', flag: '🇵🇳', phoneCode: '+64' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷', phoneCode: '+1' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', phoneCode: '+970' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', phoneCode: '+351' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', phoneCode: '+680' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', phoneCode: '+595' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', phoneCode: '+974' },
  { code: 'RE', name: 'Réunion', flag: '🇷🇪', phoneCode: '+262' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', phoneCode: '+40' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', phoneCode: '+381' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', phoneCode: '+7' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', phoneCode: '+250' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', phoneCode: '+966' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', phoneCode: '+677' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', phoneCode: '+248' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', phoneCode: '+249' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', phoneCode: '+46' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', phoneCode: '+65' },
  { code: 'SH', name: 'Saint Helena', flag: '🇸🇭', phoneCode: '+290' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', phoneCode: '+386' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯', phoneCode: '+47' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', phoneCode: '+421' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', phoneCode: '+232' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', phoneCode: '+378' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', phoneCode: '+221' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', phoneCode: '+252' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', phoneCode: '+597' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', phoneCode: '+211' },
  { code: 'ST', name: 'São Tomé and Príncipe', flag: '🇸🇹', phoneCode: '+239' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', phoneCode: '+503' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽', phoneCode: '+1' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', phoneCode: '+963' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', phoneCode: '+268' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨', phoneCode: '+1' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', phoneCode: '+235' },
  { code: 'TF', name: 'French Southern Territories', flag: '🇹🇫', phoneCode: '+262' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', phoneCode: '+228' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', phoneCode: '+66' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', phoneCode: '+992' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰', phoneCode: '+690' },
  { code: 'TL', name: 'East Timor', flag: '🇹🇱', phoneCode: '+670' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', phoneCode: '+993' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', phoneCode: '+216' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', phoneCode: '+676' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', phoneCode: '+90' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', phoneCode: '+1' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', phoneCode: '+688' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', phoneCode: '+886' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', phoneCode: '+255' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', phoneCode: '+380' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', phoneCode: '+256' },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', flag: '🇺🇲', phoneCode: '+1' },
  { code: 'US', name: 'United States', flag: '🇺🇸', phoneCode: '+1' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', phoneCode: '+598' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', phoneCode: '+998' },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦', phoneCode: '+39' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', phoneCode: '+1' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', phoneCode: '+58' },
  { code: 'VG', name: 'British Virgin Islands', flag: '🇻🇬', phoneCode: '+1' },
  { code: 'VI', name: 'U.S. Virgin Islands', flag: '🇻🇮', phoneCode: '+1' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', phoneCode: '+84' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', phoneCode: '+678' },
  { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫', phoneCode: '+681' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', phoneCode: '+685' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', phoneCode: '+967' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹', phoneCode: '+262' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', phoneCode: '+27' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', phoneCode: '+260' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', phoneCode: '+263' },
];

export const majorCities: City[] = [
  // United States
  { name: 'New York', country: 'US' },
  { name: 'Los Angeles', country: 'US' },
  { name: 'Chicago', country: 'US' },
  { name: 'Houston', country: 'US' },
  { name: 'Phoenix', country: 'US' },
  { name: 'Philadelphia', country: 'US' },
  { name: 'San Antonio', country: 'US' },
  { name: 'San Diego', country: 'US' },
  { name: 'Dallas', country: 'US' },
  { name: 'San Jose', country: 'US' },
  { name: 'Austin', country: 'US' },
  { name: 'Jacksonville', country: 'US' },
  { name: 'San Francisco', country: 'US' },
  { name: 'Columbus', country: 'US' },
  { name: 'Charlotte', country: 'US' },
  { name: 'Fort Worth', country: 'US' },
  { name: 'Indianapolis', country: 'US' },
  { name: 'Seattle', country: 'US' },
  { name: 'Denver', country: 'US' },
  { name: 'Washington', country: 'US' },
  { name: 'Boston', country: 'US' },
  { name: 'El Paso', country: 'US' },
  { name: 'Nashville', country: 'US' },
  { name: 'Detroit', country: 'US' },
  { name: 'Oklahoma City', country: 'US' },
  { name: 'Portland', country: 'US' },
  { name: 'Las Vegas', country: 'US' },
  { name: 'Memphis', country: 'US' },
  { name: 'Louisville', country: 'US' },
  { name: 'Baltimore', country: 'US' },
  { name: 'Milwaukee', country: 'US' },
  { name: 'Albuquerque', country: 'US' },
  { name: 'Tucson', country: 'US' },
  { name: 'Fresno', country: 'US' },
  { name: 'Mesa', country: 'US' },
  { name: 'Sacramento', country: 'US' },
  { name: 'Atlanta', country: 'US' },
  { name: 'Kansas City', country: 'US' },
  { name: 'Colorado Springs', country: 'US' },
  { name: 'Miami', country: 'US' },
  { name: 'Raleigh', country: 'US' },
  { name: 'Omaha', country: 'US' },
  { name: 'Long Beach', country: 'US' },
  { name: 'Virginia Beach', country: 'US' },
  { name: 'Oakland', country: 'US' },
  { name: 'Minneapolis', country: 'US' },
  { name: 'Tulsa', country: 'US' },
  { name: 'Arlington', country: 'US' },
  { name: 'Tampa', country: 'US' },

  // Canada
  { name: 'Toronto', country: 'CA' },
  { name: 'Montreal', country: 'CA' },
  { name: 'Vancouver', country: 'CA' },
  { name: 'Calgary', country: 'CA' },
  { name: 'Edmonton', country: 'CA' },
  { name: 'Ottawa', country: 'CA' },
  { name: 'Mississauga', country: 'CA' },
  { name: 'Winnipeg', country: 'CA' },
  { name: 'Quebec City', country: 'CA' },
  { name: 'Hamilton', country: 'CA' },
  { name: 'Brampton', country: 'CA' },
  { name: 'Surrey', country: 'CA' },
  { name: 'Laval', country: 'CA' },
  { name: 'Halifax', country: 'CA' },
  { name: 'London', country: 'CA' },
  { name: 'Markham', country: 'CA' },
  { name: 'Vaughan', country: 'CA' },
  { name: 'Gatineau', country: 'CA' },
  { name: 'Saskatoon', country: 'CA' },
  { name: 'Longueuil', country: 'CA' },

  // United Kingdom
  { name: 'London', country: 'GB' },
  { name: 'Birmingham', country: 'GB' },
  { name: 'Manchester', country: 'GB' },
  { name: 'Glasgow', country: 'GB' },
  { name: 'Liverpool', country: 'GB' },
  { name: 'Bristol', country: 'GB' },
  { name: 'Sheffield', country: 'GB' },
  { name: 'Leeds', country: 'GB' },
  { name: 'Edinburgh', country: 'GB' },
  { name: 'Leicester', country: 'GB' },
  { name: 'Coventry', country: 'GB' },
  { name: 'Bradford', country: 'GB' },
  { name: 'Cardiff', country: 'GB' },
  { name: 'Belfast', country: 'GB' },
  { name: 'Nottingham', country: 'GB' },
  { name: 'Hull', country: 'GB' },
  { name: 'Newcastle', country: 'GB' },
  { name: 'Stoke-on-Trent', country: 'GB' },
  { name: 'Southampton', country: 'GB' },
  { name: 'Derby', country: 'GB' },

  // Germany
  { name: 'Berlin', country: 'DE' },
  { name: 'Hamburg', country: 'DE' },
  { name: 'Munich', country: 'DE' },
  { name: 'Cologne', country: 'DE' },
  { name: 'Frankfurt', country: 'DE' },
  { name: 'Stuttgart', country: 'DE' },
  { name: 'Düsseldorf', country: 'DE' },
  { name: 'Leipzig', country: 'DE' },
  { name: 'Dortmund', country: 'DE' },
  { name: 'Essen', country: 'DE' },
  { name: 'Bremen', country: 'DE' },
  { name: 'Dresden', country: 'DE' },
  { name: 'Hanover', country: 'DE' },
  { name: 'Nuremberg', country: 'DE' },
  { name: 'Duisburg', country: 'DE' },
  { name: 'Bochum', country: 'DE' },
  { name: 'Wuppertal', country: 'DE' },
  { name: 'Bielefeld', country: 'DE' },
  { name: 'Bonn', country: 'DE' },
  { name: 'Mannheim', country: 'DE' },

  // France
  { name: 'Paris', country: 'FR' },
  { name: 'Marseille', country: 'FR' },
  { name: 'Lyon', country: 'FR' },
  { name: 'Toulouse', country: 'FR' },
  { name: 'Nice', country: 'FR' },
  { name: 'Nantes', country: 'FR' },
  { name: 'Montpellier', country: 'FR' },
  { name: 'Strasbourg', country: 'FR' },
  { name: 'Bordeaux', country: 'FR' },
  { name: 'Lille', country: 'FR' },
  { name: 'Rennes', country: 'FR' },
  { name: 'Reims', country: 'FR' },
  { name: 'Saint-Étienne', country: 'FR' },
  { name: 'Toulon', country: 'FR' },
  { name: 'Le Havre', country: 'FR' },
  { name: 'Grenoble', country: 'FR' },
  { name: 'Dijon', country: 'FR' },
  { name: 'Angers', country: 'FR' },
  { name: 'Nîmes', country: 'FR' },
  { name: 'Villeurbanne', country: 'FR' },

  // Spain
  { name: 'Madrid', country: 'ES' },
  { name: 'Barcelona', country: 'ES' },
  { name: 'Valencia', country: 'ES' },
  { name: 'Seville', country: 'ES' },
  { name: 'Zaragoza', country: 'ES' },
  { name: 'Málaga', country: 'ES' },
  { name: 'Murcia', country: 'ES' },
  { name: 'Palma', country: 'ES' },
  { name: 'Las Palmas', country: 'ES' },
  { name: 'Bilbao', country: 'ES' },
  { name: 'Alicante', country: 'ES' },
  { name: 'Córdoba', country: 'ES' },
  { name: 'Valladolid', country: 'ES' },
  { name: 'Vigo', country: 'ES' },
  { name: 'Gijón', country: 'ES' },
  { name: 'Hospitalet', country: 'ES' },
  { name: 'Granada', country: 'ES' },
  { name: 'Vitoria', country: 'ES' },
  { name: 'A Coruña', country: 'ES' },
  { name: 'Elche', country: 'ES' },

  // Italy
  { name: 'Rome', country: 'IT' },
  { name: 'Milan', country: 'IT' },
  { name: 'Naples', country: 'IT' },
  { name: 'Turin', country: 'IT' },
  { name: 'Palermo', country: 'IT' },
  { name: 'Genoa', country: 'IT' },
  { name: 'Bologna', country: 'IT' },
  { name: 'Florence', country: 'IT' },
  { name: 'Bari', country: 'IT' },
  { name: 'Catania', country: 'IT' },
  { name: 'Venice', country: 'IT' },
  { name: 'Verona', country: 'IT' },
  { name: 'Messina', country: 'IT' },
  { name: 'Padua', country: 'IT' },
  { name: 'Trieste', country: 'IT' },
  { name: 'Taranto', country: 'IT' },
  { name: 'Brescia', country: 'IT' },
  { name: 'Parma', country: 'IT' },
  { name: 'Reggio Calabria', country: 'IT' },
  { name: 'Modena', country: 'IT' },

  // Australia
  { name: 'Sydney', country: 'AU' },
  { name: 'Melbourne', country: 'AU' },
  { name: 'Brisbane', country: 'AU' },
  { name: 'Perth', country: 'AU' },
  { name: 'Adelaide', country: 'AU' },
  { name: 'Gold Coast', country: 'AU' },
  { name: 'Newcastle', country: 'AU' },
  { name: 'Canberra', country: 'AU' },
  { name: 'Wollongong', country: 'AU' },
  { name: 'Logan City', country: 'AU' },
  { name: 'Geelong', country: 'AU' },
  { name: 'Townsville', country: 'AU' },
  { name: 'Cairns', country: 'AU' },
  { name: 'Toowoomba', country: 'AU' },
  { name: 'Darwin', country: 'AU' },
  { name: 'Rockingham', country: 'AU' },
  { name: 'Launceston', country: 'AU' },
  { name: 'Bendigo', country: 'AU' },
  { name: 'Ballarat', country: 'AU' },
  { name: 'Mandurah', country: 'AU' },

  // India
  { name: 'Mumbai', country: 'IN' },
  { name: 'Delhi', country: 'IN' },
  { name: 'Bangalore', country: 'IN' },
  { name: 'Hyderabad', country: 'IN' },
  { name: 'Chennai', country: 'IN' },
  { name: 'Kolkata', country: 'IN' },
  { name: 'Surat', country: 'IN' },
  { name: 'Pune', country: 'IN' },
  { name: 'Jaipur', country: 'IN' },
  { name: 'Lucknow', country: 'IN' },
  { name: 'Kanpur', country: 'IN' },
  { name: 'Nagpur', country: 'IN' },
  { name: 'Indore', country: 'IN' },
  { name: 'Thane', country: 'IN' },
  { name: 'Bhopal', country: 'IN' },
  { name: 'Visakhapatnam', country: 'IN' },
  { name: 'Vadodara', country: 'IN' },
  { name: 'Firozabad', country: 'IN' },
  { name: 'Ludhiana', country: 'IN' },
  { name: 'Rajkot', country: 'IN' },

  // China
  { name: 'Shanghai', country: 'CN' },
  { name: 'Beijing', country: 'CN' },
  { name: 'Chongqing', country: 'CN' },
  { name: 'Tianjin', country: 'CN' },
  { name: 'Guangzhou', country: 'CN' },
  { name: 'Shenzhen', country: 'CN' },
  { name: 'Wuhan', country: 'CN' },
  { name: 'Dongguan', country: 'CN' },
  { name: 'Chengdu', country: 'CN' },
  { name: 'Nanjing', country: 'CN' },
  { name: 'Foshan', country: 'CN' },
  { name: 'Shenyang', country: 'CN' },
  { name: 'Hangzhou', country: 'CN' },
  { name: 'Xi\'an', country: 'CN' },
  { name: 'Harbin', country: 'CN' },
  { name: 'Suzhou', country: 'CN' },
  { name: 'Qingdao', country: 'CN' },
  { name: 'Dalian', country: 'CN' },
  { name: 'Zhengzhou', country: 'CN' },
  { name: 'Shantou', country: 'CN' },

  // Japan
  { name: 'Tokyo', country: 'JP' },
  { name: 'Yokohama', country: 'JP' },
  { name: 'Osaka', country: 'JP' },
  { name: 'Nagoya', country: 'JP' },
  { name: 'Sapporo', country: 'JP' },
  { name: 'Fukuoka', country: 'JP' },
  { name: 'Kobe', country: 'JP' },
  { name: 'Kawasaki', country: 'JP' },
  { name: 'Kyoto', country: 'JP' },
  { name: 'Saitama', country: 'JP' },
  { name: 'Hiroshima', country: 'JP' },
  { name: 'Sendai', country: 'JP' },
  { name: 'Kitakyushu', country: 'JP' },
  { name: 'Chiba', country: 'JP' },
  { name: 'Sakai', country: 'JP' },
  { name: 'Niigata', country: 'JP' },
  { name: 'Hamamatsu', country: 'JP' },
  { name: 'Okayama', country: 'JP' },
  { name: 'Sagamihara', country: 'JP' },
  { name: 'Kumamoto', country: 'JP' },

  // Brazil
  { name: 'São Paulo', country: 'BR' },
  { name: 'Rio de Janeiro', country: 'BR' },
  { name: 'Salvador', country: 'BR' },
  { name: 'Brasília', country: 'BR' },
  { name: 'Fortaleza', country: 'BR' },
  { name: 'Belo Horizonte', country: 'BR' },
  { name: 'Manaus', country: 'BR' },
  { name: 'Curitiba', country: 'BR' },
  { name: 'Recife', country: 'BR' },
  { name: 'Goiânia', country: 'BR' },
  { name: 'Belém', country: 'BR' },
  { name: 'Porto Alegre', country: 'BR' },
  { name: 'Guarulhos', country: 'BR' },
  { name: 'Campinas', country: 'BR' },
  { name: 'São Luís', country: 'BR' },
  { name: 'São Gonçalo', country: 'BR' },
  { name: 'Maceió', country: 'BR' },
  { name: 'Duque de Caxias', country: 'BR' },
  { name: 'Natal', country: 'BR' },
  { name: 'Teresina', country: 'BR' },

  // Add more cities as needed
].sort((a, b) => a.name.localeCompare(b.name));

export function getCountryByCode(code: string): Country | undefined {
  return countries.find(country => country.code === code);
}

export function getCitiesByCountry(countryCode: string): City[] {
  return majorCities.filter(city => city.country === countryCode);
}

export function searchCountries(query: string): Country[] {
  const lowerQuery = query.toLowerCase();
  return countries.filter(country => 
    country.name.toLowerCase().includes(lowerQuery) ||
    country.code.toLowerCase().includes(lowerQuery) ||
    country.phoneCode.includes(query)
  );
}

export function searchCities(query: string, countryCode?: string): City[] {
  const lowerQuery = query.toLowerCase();
  let filtered = majorCities.filter(city => 
    city.name.toLowerCase().includes(lowerQuery)
  );
  
  if (countryCode) {
    filtered = filtered.filter(city => city.country === countryCode);
  }
  
  return filtered;
}